[[docs]]
  name = "关于重力中国"
  weight = 1
  identifier = "about"
  url = "/about/"

[[docs]]
  name = "重力学入门"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started/"

[[docs]]
  name = "重力软件教程"
  weight = 10
  identifier = "gravity-manual"
  url = "/gravity-manual/"

[[docs]]
  name = "重力数据处理教程"
  weight = 15
  identifier = "gravitydata"
  url = "/gravitydata/"
[[docs]]
  name = "重力开源软件开发"
  weight = 36
  identifier = "gravity-software"
  url = "/gravity-software/"
[[docs]]
  name = "重力项目展示"
  weight = 40
  post = "break"
  identifier = "commands"
  url = "/gravity-projects/"



# LOW LEVEL ITEMS


[[docs]]
  name = "Troubleshooting"
  weight = 60
  identifier = "troubleshooting"
  url = "/troubleshooting/"

[[docs]]
  name = "Tools"
  weight = 70
  identifier = "tools"
  url = "/tools/"

[[docs]]
  name = "Hosting & Deployment"
  weight = 80
  identifier = "hosting-and-deployment"
  url = "/hosting-and-deployment/"

[[docs]]
  name = "Contribute"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/contribute/"

#[[docs]]
#  name = "Tags"
#  weight = 120
#  identifier = "tags"
#  url = "/tags/"


# [[docs]]
#   name = "Categories"
#   weight = 140
#   identifier = "categories"
#   url = "/categories/"

######## QUICKLINKS

  [[quicklinks]]
    name = "Fundamentals"
    weight = 1
    identifier = "fundamentals"
    url = "/tags/fundamentals/"




######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "新闻"
    weight = 1
    identifier = "news"
    url = "/news/"

  [[global]]
    name = "文档"
    weight = 5
    identifier = "docs"
    url = "/documentation/"

  [[global]]
    name = "关于我们"
    weight = 220
    identifier = "themes"
    url = "/about/"

    [[global]]
      name = "研究案例"
      weight = 20
      identifier = "showcase"
      url = "/gravity-projects/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "重力论坛"
    weight = 120
    icon = true
    identifier = "community"
    post = "external"
    url = "https://discourse.gravitychina.ga/"


  [[global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/Gravity-Geodesy-China-Community"
